# Линейная алгебра. Лабораторная работа 1, осень 2022


В этой лабораторной работе вы познакомитесь со средой Jupyter Notebook и библиотеками numpy и scipy.

## Часть 1. Библиотеки

В этой лабораторной работе вам понадобятся три библиотеки:

- `numpy` – основная библиотека для работы с матрицами;
- `scipy`, а точнее модуль `scipy.linalg`, содержащий множество функций линейной алгебры;
- `matplotlib` – графическая библиотека

Подключить их можно следующим образом:

In [1]:
# Запустите этот код
import numpy as np

import scipy.linalg as sla

import matplotlib.pyplot as plt
%matplotlib inline

Теперь вы можете позвать, скажем, функцию `scipy.linalg.det()` с помощью кода `sla.det()`, а функцию `numpy.exp()` – с помощью кода `np.exp()`.

**Основные объекты и операции линейной алгебры в NumPy и SciPy:**

Основной объект, с которым вам придётся работать и в этой, и в следующих лабораторных, – это, безусловно, матрицы. В библиотеке `numpy` они представлены классом `numpy.ndarray`. Матрицу можно создать из двумерного (а на самом деле и не только двумерного) массива следующим образом:

In [3]:
# Запустите этот код
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A)
print(A.shape) # пара (число строк, число столбцов)

[[1 2 3]
 [4 5 6]]
(2, 3)


Обратите внимание, что матрица заполняется *по строкам*.

Есть и много других конструкторов матриц. Например, единичная матрица размера $n\times n$ создаётся с помощью функции `numpy.eye(n)`. Со всем многообразием конструкторов можно ознакомиться [на этой странице](https://docs.scipy.org/doc/numpy-1.10.1/reference/routines.array-creation.html).

Зачастую бывает нужно получить доступ к подматрицам данной матрицы, и numpy предоставляет множество удобных средств, как это сделать (вообще данная процедура называется slicing):
- элемент с номером `(i,j)`: `A[i,j]`
- i-я строка матрицы: `A[i,:]`
- j-й столбец матрицы: `A[:,j]`

**Внимание!** Оба варианта, и `A[i,:]`, и `A[:,j]` дают не строку или столбец, а одномерный вектор. Если вы хотите получить вектор-строку или вектор-столбец соответственно, используйте вот такой синтаксис: `A[i:i+1,:]` и `A[:,j:j+1]`
- строки с нулевой по i-ю: `A[:i+1,:]`
- столбцы с j-го по последний: `A[:,j:]`
- строки с i-й по k-ю: `A[i:k,:]`

В некоторых случаях нужно получить доступ к (прямоугольной) подматрице, элементы которой находятся на пересечении строк из списка `rows` и столбцов из списка `columns`. В этом случае `A[rows, columns]` даст не то, что вы ожидаете (можете попробовать это сделать сами и увидеть, что получится; только возьмите `rows` и `columns` одного размера). Справиться с этой задачей позволяет код `A[np.ix_(rows, columns)]`

*Умножение матриц* производится с помощью функции `np.dot()` либо оператора `@`. Есть три варианта написания: `A.dot(B)`, `np.dot(A, B)` и `A @ B`.

Обычные знаки арифметических действий (`+`, `-`, `*`) зарезервированы для поэлементных операций. Например, `A * B` – это матрица, элементами которой являются произведения $A_{ij}B_{ij}$. Помимо этих есть и множество других поэлементных операций. Например, `numpy.exp(A)` – это матрица, элементами которой являются экспоненты элементов матрицы `A`.

Чтобы получить матрицу, *транспонированную* к матрице `A`, напишите просто `A.T`. 

В некоторых случаях бывает нужно создавать *случайные матрицы*: например, при проведении экспериментов или для инициализации итеративных методов. Средства для этого предоставляет пакет [numpy.random](https://docs.scipy.org/doc/numpy/reference/routines.random.html). Так, `np.random.rand(m,n)` – это матрица $m\times n$, элементы которой независимо выбраны из равномерного распределения на интервале `[0;1)`.

Для *решения систем линейных уравнений* в пакете `scipy.linalg` есть множество методов, рассмотрение которых выходит за пределы стандартного курса линейной алгебры. Мы вам пока предлагаем пользоваться функцией `scipy.linalg.solve`, основанной на методе Гаусса. Отметим, что `scipy.linalg.solve(A, B)` выдаёт решение уравнения $AX = B$ (или ошибку), где $B$ может быть как вектором, так и матрицей.

Найти обратную матрицу для матрицы $A$ можно с помощью функции `sla.inv(A)`.

**Копирование сложных объектов в Python**

Когда вы делаете присваивание каких-то сложных объектов, как правило, оно происходит по ссылке. Например, код
```
B = A
B[0,0] = 10
```
приведёт к изменению матрицы `A`.

Не попадайтесь в эту ловушку! Если вы хотите работать с копией как с независимой матрицей, используйте метод `copy()`:
```
B = A.copy()
```

**Где искать помощь**

Библиотеки `numpy` и `scipy` снабжены прекрасной документацией. Если у вас возникают вопросы о том, как работает та или иная функция (или даже как называется функция, выполняющая то, что вам нужно), вы почти всегда можете найти там ответы.

[Ссылка на документацию пакета scipy.linalg](https://docs.scipy.org/doc/scipy-0.18.1/reference/linalg.html)

Если у вас возникает какая-то ошибка и вы не можете понять, что вы делаете не так, то

1) в первую очередь попробуйте просто загуглить текст ошибки, наверняка в интернете кто-то уже сталкивался с такой ситуацией;  
2) поспрашивайте своих одногруппников, не было ли у них такой ошибки, и если была, то как они справлялись;  
3) попросите помощи у вашего учебного ассистента.




**И всё-таки задание**

**Задание 1.1 [0.2 балла за каждый пункт]** В качестве первого задания мы попросим вас отыскать соответствующие функции в библиотеке и сделать следующее:

- создайте нулевую матрицу $Z$ размера $3\times4$;

- создайте диагональную матрицу $5\times5$ с диагональными элементами 1, 2, 3, 4 и 5;

- найдите её след (не силою мысли, а с помощью библиотечных функций, конечно);

- найдите обратную к ней матрицу;

- сгенерируйте случайную матрицу $X$ размера $4\times5$;

- найдите определитель подматрицы матрицы $X$, расположенной на пересечении 2-й и 3-й строк и 1-го и 2-го столбцов; считаем, что строки и столбцы нумеруются с единицы (используйте slicing!). Такой определитель называется **минором** матрицы $X$;

- найдите произведение $X^TX$.

Пожалуйста, каждый пункт делайте в новом блоке и не забывайте распечатывать результаты.

In [68]:
import numpy as np

import scipy.linalg as sla

import matplotlib.pyplot as plt
%matplotlib inline

#нулевая матрица
z = np.zeros((3, 4),int)
print(z)

#диагональная матрица
a = np.zeros((5, 5), int)
diag = np.array([1, 2, 3, 4, 5])
np.fill_diagonal(a, diag)
print(a)

#след
print(np.trace(a))

#обратная матрица
b = np.linalg.inv(a)
print(b)

#случайная
x = np.array(np.random.randint(30, size=(4, 5)))
print(x)

#определитель подматрицы
y = x[np.ix_([1,2],[0,1])]
print(np.linalg.det(y))

#произведение
xt = np.transpose(x)
print(xt.dot(x))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
15
[[1.         0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.        ]
 [0.         0.         0.33333333 0.         0.        ]
 [0.         0.         0.         0.25       0.        ]
 [0.         0.         0.         0.         0.2       ]]
[[ 0  7  7 23  2]
 [26  0 22 24 21]
 [14 16 15 20  0]
 [20 11 14  9 14]]
416.0
[[1272  444 1062 1084  826]
 [ 444  426  443  580  168]
 [1062  443  954 1115  672]
 [1084  580 1115 1586  676]
 [ 826  168  672  676  641]]


## Часть 2. Время

Питон мотивирует пользоваться библиотечными функциями, когда они доступны, а не писать собственные. Библиотечные функции основаны на современных алгоритмах, обычно пишутся на более эффективных языках, таких как C++ или Fortran, а кроме того, оптимизированы для работы на многопроцессорных устройствах, так что обогнать эти решения просто так вы не сможете.

**Задание 2.1 [1 балл]**
Мы предлагаем вам убедиться в этом самим. Напишите функцию `my_det`, которая вычисляла бы определитель матрицы с помощью элементарных преобразований над строками. Функция должна выкидывать `ValueError` в случаях, если матрица не является квадратной.

In [85]:

import numpy as np

import scipy.linalg as sla

import matplotlib.pyplot as plt
import math
%matplotlib inline


def maxel(x, first, second):  
    global znak
    m = x[first].copy()
    t = x[second].copy()
    if first != second:
        znak = znak * (-1)
    x[first], x[second] = t, m



def dozero(x, ind):  
    for i in range(ind + 1, len(x)):
        umnoz = -x[i][ind]
        if x[ind][ind] != 0:
            x[i] = [(f + g / x[ind][ind] * umnoz) for f, g in zip(x[i], x[ind])]


def ulstupvid(x):
    if len(x) != len(x[0]):
        raise ValueError
    else:
        ind = 0
        while ind < len(x):
            now = -1
            for i in range(ind, len(x)):
                if now == -1 or abs(x[i][ind])>abs(x[now][ind]):
                    now = i
            maxel(x,now,ind)
            
            dozero(x, ind)
            ind += 1
    return x


def my_det(x):
    global znak
    x = ulstupvid(x)
    ans = 1 * znak
    for i in range(len(x)):
        ans = ans * x[i][i]
    return ans



x = np.array(np.random.randint(10, size=(3, 3)))
print(x)

znak = 1
ind = 0
i = 2


print(ulstupvid(x))
print(my_det(x))








[[6 7 5]
 [3 8 4]
 [2 4 0]]
[[ 6  7  5]
 [ 0  4  1]
 [ 0  0 -1]]
-24


Простая проверка:

In [10]:

import numpy as np

import scipy.linalg as sla

import matplotlib.pyplot as plt
import math
%matplotlib inline


def maxel(x, ind):  # переносит строку с наибольшем числом наверх
    global znak
    maxx = -39044094829008989
    numbstr = 0
    ind = 0
    for i in range(len(x)):
        if x[i][ind] > maxx:
            maxx = x[i][ind]
            numbstr = i
    m = x[numbstr].copy()
    t = x[ind].copy()
    if numbstr != ind:
        znak += 1
    x[numbstr], x[ind] = t, m
    return x





def dozero(x, i, ind, umnoz):  # делаем нули
    if x[ind][ind]!=0:
            x[i] = [(a + k / x[ind][ind] * umnoz) for a, k in zip(x[i], x[ind])]
    

def ulstupvid(x):
    if len(x) != len(x[0]):
        raise ValueError
    else:
        ind = 0
        while ind < len(x):
            x = maxel(x, ind)
            for i in range(ind + 1, len(x)):
                dozero(x, i, ind, -x[i][ind])
            ind += 1
    return x

def my_det(x):
    global znak
    x = ulstupvid(x)
    ans = 1 * (-1)**znak
    for i in range(len(x)):
        ans = ans * x[i][i]
    return ans


znak = 0
ind = 0
i = 2

x = np.array([[0,0,1], [0,1,0], [1,0,0]])
print(my_det(x))

-1


Теперь давайте сравним скорость работы вашей функции и библиотечной функции `scipy.linalg.det`. В Питоне есть несколько способов измерения времени; мы воспользуемся декоратором `%timeit`. Будучи написан перед функцией, он запускает её некоторое количество раз, выбирает три случайных запуска и возвращает длительность самого быстрого из них. Модификатор `-o` между декоратором и функцией позволяет сохранять результаты работы декоратора в переменную.

Приготовьтесь, что следующий блок может работать сравнительно долго.

In [ ]:
# Запустите этот блок кода
lib_times = []
my_times = []
dimensions = [10, 100, 1000]
for dim in dimensions:
    A = np.random.rand(dim, dim)
    res_lib = %timeit -o sla.det(A)
    lib_times.append(res_lib.best)
    res_my = %timeit -o my_det(A)
    my_times.append(res_my.best)    

plt.plot(dimensions, lib_times, color='blue', label='Library function')
plt.plot(dimensions, my_times, color='red', label='My function')
plt.title('My function vs library function, log y scale')
plt.ylabel('Time')
plt.xlabel('Matrix dimension')
plt.legend()

У вас должны были получиться графики, показывающие, как растёт с ростом размерности матрицы время вычисления определителя. Поскольку они вышли не больно-то красивыми, мы нарисуем их в *логарифмическом масштабе* по оси у:

In [ ]:
# Запустите этот блок кода
plt.semilogy(dimensions, lib_times, color='blue', label='Library function')
plt.semilogy(dimensions, my_times, color='red', label='My function')
plt.title('My function vs library function, log y scale')
plt.ylabel('Time')
plt.xlabel('Matrix dimension')
plt.legend()

Вы можете убедиться, что библиотечная функция работает *гораздо* быстрее.

## Часть 3. Точность

Наверняка вы уже что-то знаете про floating point arithmetics и связанные с этим трудности и понимаете, что на компьютере вычисления с вещественными числами производятся лишь с ограниченной точностью. 

**Задание 3.1 [0.6 балла]** В качестве первого примера, показывающего различие между длинной арифметикой целых чисел и floating point arithmetics, предлагаем вам перемножить две пары матриц:

$$
\begin{pmatrix}
1 & 0\\
10^{20} & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
10^{-20} & 1\\
0 & 1 - 10^{20}
\end{pmatrix}
$$
и
$$
\begin{pmatrix}
1. & 0.\\
10.^{20} & 1.
\end{pmatrix}
\cdot
\begin{pmatrix}
10.^{-20} & 1.\\
0. & 1. - 10.^{20}
\end{pmatrix}
$$
Во втором случае мы специально указали Питону (поставив везде десятичные точки), что хотим работать не с целыми числами, а с числами с плавающей точкой. Посмотрим, получатся ли одинаковые ответы:

In [40]:
# Your code here
import numpy as np

import scipy.linalg as sla

import matplotlib.pyplot as plt
%matplotlib inline


a = np.array([[1,0],[10**20,1]])
b = np.array([[10**(-20),1],[0,1-10**20]])
aa = np.array(([[1,0],[10**20,1]]),float)
bb = np.array(([[10**(-20),1],[0,1-10**20]]),float)
print(a.dot(b))
print(aa.dot(bb))

[[1e-20 1]
 [1.0 1]]
[[1.e-20 1.e+00]
 [1.e+00 0.e+00]]


И какой из них правильный?

---
**Напишите здесь свой ответ** 1 вариант, так как при использовании чисел с плавающей точкой происходит перевод в двоичную систему. Двоичное число недостаточно точно представляет исходное число

**Задание 3.2 [0.75 балла]** Впрочем, и с целыми числами тоже не всегда всё хорошо. Напишите функцию, генерирующую *матрицу Паскаля* заданной размерности $n$, то есть матрицу $P$, в которой $P_{ij} = C_{i+j}^i$. В этом задании нельзя пользоваться библиотечной функцией `scipy.linalg.pascal` или её аналогами из других библиотек. Обратите внимание, что использование факториалов крайне нежелательно, так как быстро приведёт к переполнению.

В этом задании вы можете использовать цикл ``for``.

In [61]:
def my_pascal(dim):
    '''
    Мы создали для вас матрицу из нулей размера dim x dim,
    но вы можете ей не пользоваться, если не хотите
    '''
    #P = np.zeros((dim, dim))
    
    # Your code here
    P = [[1]*dim for i in range(dim)]
    for i in range(1, dim):
        for j in range(1, dim):
            P[i][j] = P[i-1][j] + P[i][j-1]
    return P
    
    
n = int(input())
my_pascal(n)


 5


[[1, 1, 1, 1, 1],
 [1, 2, 3, 4, 5],
 [1, 3, 6, 10, 15],
 [1, 4, 10, 20, 35],
 [1, 5, 15, 35, 70]]

Чему равен её определитель? **Строго** поясните свой ответ.

----
**Ваше решение** С помощью элементарных преобразований симметричную матрицу Паскаля можно привести к верхнетреугольному и нижнетреугольному виду, где на главной диагонали стоят единички (получается, что определитель обеих матриц равен 1). Заметим, что симметричная матрица Паскаля равна произведению этих двух матриц, получается, что и её определитель равен 1.

А теперь вычислите определитель матрицы Паскаля $30\times30$ с помощью библиотечной функции `scipy.linalg.det`:

In [62]:
# Your code here
import numpy as np

import scipy.linalg as sla

import matplotlib.pyplot as plt
%matplotlib inline

def my_pascal(dim):
    P = [[1]*dim for i in range(dim)]
    for i in range(1, dim):
        for j in range(1, dim):
            P[i][j] = P[i-1][j] + P[i][j-1]
    return P
    

print(np.linalg.det(my_pascal(30)))



-7.109158315047058e+49


Разница заметна невооружённым взглядом!

## Часть 4. Матричные вычисления

Вы уже видели, что использования циклов (и самописных вычислений в целом) в Питоне лучше по возможности избегать, и важно уметь находить способы делать всё библиотечными средствами.

В качестве примера рассмотрим две задачи:

**1.** Предположим, нужно вычислить суммы элементов в каждой строке матрицы `A`. Ясно, что можно написать простую функцию с двумя циклами, которая это посчитает, но так лучше не делать. Правильный способ такой:
```
A.sum(axis=1)
```
Параметр `axis=1` означает, что суммы берутся по строкам. Если вы хотите просуммировать по столбцам, укажите `axis=0`. Если вообще пропустить параметр `axis` (вызвать `A.sum()`), то функция вернёт сумму *всех* элементов матрицы.

**2.** Теперь допустим, что нам нужно каждый столбец матрицы `A` умножить на некоторое число. Более точно, пусть у нас есть (одномерный) вектор `w = np.array([w_1,...,w_n])`, и мы должны `i`-й столбец `A` умножить на число `w_i`. Опять же, это можно сделать в пару циклов, но лучше использовать операцию поэлементного умножения:
```
A * w.reshape((1,n))
```
Оператор `reshape` нужен для того, чтобы из одномерного вектора сделать вектор-строку.

Аналогично, если на числа `w_1,...,w_n` умножаются *строки* матрицы, нужно превратить `w` в вектор-столбец:
```
A * w.reshape((n,1))
```

Дальше вам будет предложено попрактиковаться в матричных вычислениях. В следующих трёх заданиях нельзя пользоваться циклами, а также конструкциями `map` и `reduce` и им подобными; вместо этого постарайтесь свести всё к матричным операциям из `numpy` (но, опять же, не `np.vectorize` или чему-то подобному). Чтобы убедиться, что получилось именно то, что нужно, пишите собственные тесты со случайными матрицами.

**Задание 4.1 [0.75 балла]** Напишите функцию `prod_and_sq_sum(A)`, вычисляющую произведение диагональных элементов, а также сумму квадратов диагональных элементов квадратной матрицы `A`.

In [177]:
# Your code here
import numpy as np

import scipy.linalg as sla

import matplotlib.pyplot as plt
%matplotlib inline


def prod_and_sq_sum(a):
    t = np.diag(a)
    b = np.diag(np.square(a))
    return t.prod(), b.sum()
    
    
x = np.array(np.random.randint(5, size=(4, 4)))
print(x)
print(*prod_and_sq_sum(x))


[[4 2 3 4]
 [3 3 3 4]
 [3 1 1 3]
 [3 0 4 4]]
48 42


**Задание 4.2 [0.75 балла]** Для матриц `A` и `B` размера $m\times n$ обозначим через $a_1,\ldots,a_n$ и $b_1,\ldots,b_n$ соответственно их столбцы; пусть также $\lambda_1, \ldots, \lambda_n$ – некоторые числа. Напишите функцию `f(A, B, lmbd, k)`, вычисляющую

$$\sum_{i=1}^{\min(k,n)}\lambda_ia_ib_i^T$$

In [176]:
# Your code here
import numpy as np

import scipy.linalg as sla

import matplotlib.pyplot as plt
%matplotlib inline


def f(A, B, lmbd, k):
    global answ
    strok, stolb = A.shape
    k = min(k, stolb)
    if k == 1:
        stolb_a = A[:, k - 1]
        stolb_a = stolb_a.reshape(strok, 1)
        stolb_b = B[:, k - 1]
        stolb_b = stolb_b.reshape(1, strok)
        lmbd_numb = lmbd[k - 1]
        answ += lmbd_numb * (stolb_a * stolb_b)
        return answ
    else:
        stolb_a = A[:, k - 1]
        stolb_a = stolb_a.reshape(strok, 1)
        stolb_b = B[:, k - 1]
        stolb_b = stolb_b.reshape(1, strok)
        lmbd_numb = lmbd[k - 1]
        answ += lmbd_numb * (stolb_a * stolb_b)
        f(A, B, lmbd, k - 1)

        

lmbd=list(map(int, input().split()))
k = int(input())  
A = np.array(np.random.randint(10, size=(4, 4)))
print (A)
B = np.array(np.random.randint(10, size=(4, 4)))
answ = 0 
print (B)
f(A, B, lmbd, k)
print(answ)

 1 2 3 4
 2


[[0 5 4 6]
 [2 6 1 6]
 [9 5 6 6]
 [9 9 3 4]]
[[1 6 8 9]
 [3 5 5 3]
 [6 9 3 3]
 [2 1 6 3]]
[[ 60  50  90  10]
 [ 74  66 120  16]
 [ 69  77 144  28]
 [117 117 216  36]]


**Задание 4.3 [0.75 балла]** Напишите функцию `get_diag(A,B)`, принимающую две квадратных матрицы матрицы `A` и `B` одного размера и возвращающую вектор диагональных элементов произведения `AB`, не вычисляя произведение целиком. 

In [165]:
import numpy as np
import scipy.linalg as sla
import matplotlib.pyplot as plt
%matplotlib inline

def get_diag(A,B):
    return np.sum(A * B.T, axis=1)
    
    
A = np.array(np.random.randint(5, size=(4, 4)))
B = np.array(np.random.randint(5, size=(4, 4)))
print(A)
print(B)
print(get_diag(A,B))

[[1 4 0 3]
 [2 2 2 3]
 [3 4 3 3]
 [4 3 1 4]]
[[4 2 3 4]
 [4 2 1 2]
 [1 3 0 4]
 [0 3 3 1]]
[20 23 22 30]


## Часть 5. Комплексные числа и геометрия

У вас уже была возможность убедиться, что многие операции над комплексными числами имеют наглядную геометрическую интерпретацию. В этом задании вам будет предложено этим воспользоваться.

В Python число $i$ (мнимая единица) обозначено через `1j`. Так, число $0,5 + 1,2i$ будет иметь вид `0.5 + 1.2 * 1j`.

При выполнении задания вы должны работать с точками плоскости как с комплексными числами. Любые преобразования должны быть реализованы с помощью операций над комплексными числами: сложения, вычитания, умножения, деления, возведения в степень и комплексного сопряжения.

**Задание 5.1 [0.5 баллов]** Напишите функцию `shrink_rotate`, которая принимает на вход:
- заданную в виде комплексного числа точку $X$, которую мы подвергаем преобразованию,
- заданную в виде комплексного числа точку $A$, 
- действительный коэффициент `coef`,
- угол `alpha`, заданный в радианах

и осуществляет следующее преобразование: мы берём вектор $AX$, умножаем его на `coef`, поворачиваем вокруг точки $A$ на угол `alpha` против часовой стрелки, после чего возвращаем конец полученного вектора. Ниже (левая картинка) мы приводим иллюстрацию действия этого преобразования:

<img src="ShrinkRotate.png">

**Задание 5.2 [0.5 баллов]** Напишите функцию `shrink_rotate_conj`, которая сначала делает то же самое, что и `shrink_rotate`, а после этого отражает вектор $AY$ относительно горизонтальной прямой, проходящей через точку $A$, и возвращает точку $Y'$ (см. правую часть рисунка).

**Задание 5.3 [0.5 баллов]** Напишите функцию `geometric_inverse`, которая принимает на вход:
- заданную в виде комплексного числа точку $X$, которую мы подвергаем преобразованию,
- заданную в виде комплексного числа точку $A$, 
- положительное действительное число $r$

и осуществляет инверсию точки $X$ относительно окружности с центром $A$ радиуса $r$. [Определение инверсии вы можете посмотреть здесь](https://ru.wikipedia.org/wiki/%D0%98%D0%BD%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F_(%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F)).

In [34]:
import numpy as np
import math

import scipy.linalg as sla

import matplotlib.pyplot as plt
%matplotlib inline

'''def rotate(origin, point, angle):
    ox, oy = origin
    px, py = point
    xone = ax + math.cos(angle) * (ox - ax) - math.sin(angle) * (oy - ay)
    yone = ay + math.sin(angle) * (ox - ax) + math.cos(angle) * (oy - ay)
    return qx, qy'''

def shrink_rotate(X, A, coef, angle):
    A = A * coef #mult
    X = X * coef #mult
    
    ax = A.real
    ay = A.imag
    ox = X.real
    oy = X.imag
    xone = ax + math.cos(angle) * (ox - ax) - math.sin(angle) * (oy - ay) #rotate
    yone = ay + math.sin(angle) * (ox - ax) + math.cos(angle) * (oy - ay) #rotate

    return complex(xone, yone)
    #raise NotImplementedError()
    
def shrink_rotate_conj(X, A, coef=1., angle=0.):
    A = A * coef #mult
    X = X * coef #mult
    
    ax = A.real
    ay = A.imag
    ox = X.real
    oy = X.imag
    xone = ax + math.cos(angle) * (ox - ax) - math.sin(angle) * (oy - ay) #rotate
    yone = ay + math.sin(angle) * (ox - ax) + math.cos(angle) * (oy - ay) #rotate
    p = complex(xone, yone)
    return np.conj(p)
    #raise NotImplementedError()
    
def geometric_inverse(P, A, r):
    ax = A.real
    ay = A.imag
    px = P.real
    py = P.imag
    xn = ax + (r**2*(px-ax)/((px-ax)**2+(py-ay)**2))
    yn = ay + (r**2*(py-ay)/((px-ax)**2+(py-ay)**2))
    p = complex(xn,yn)
    return p
    
    
    '''AP = ((py-ay)**2+(px-ax)**2)**0.5
    AN = r**2/AP
    coef = AN / AP
    P = P * coef
    return P
    #raise NotImplementedError()'''
    

#X = complex('1+2j')
#A = complex('0+1.5j')
r = 3.0
#X = complex('0+1,2j')
#A = complex('1+1,5j')
X = complex('1+2j')
A = complex('3+4j')
coef = 2.
angle = 1.
print(shrink_rotate(X, A, coef, angle)) 
print(shrink_rotate_conj(X, A, coef, angle))
print(geometric_inverse(X, A, r))

#shrink_rotate(X, A, coef = 1., angle = 0.)
#x = complex(input())
#a = complex(input())
#coef= float(input())
#alpha = float(input())

(7.204674715759027+2.472906837295855j)
(7.204674715759027-2.472906837295855j)
(0.75+1.75j)


**Задание 5.4 [0.75 баллов]** Рассмотрим следующий процесс:

```
z = 0.5 + 0.*1j
max_iter = 100000
funcs = [
    (lambda t: shrink_rotate(t, 0. + 1.*1j, coef=0.5, angle=0.)),
    (lambda t: shrink_rotate(t, 1. + 0.*1j, coef=0.5, angle=0.)),
    (lambda t: shrink_rotate(t, -1. + 0.*1j, coef=0.5, angle=0.))
]

for n_iter in range(max_iter):
    n_func = np.random.choice(len(funcs))
    z = funcs[n_func](z)
```

Запустите его и нарисуйте множество точек, получающихся на итерациях начиняя с десятой.

*Указание*. Представьте квадрат $[-1,1]\times[-1,1]$ матрицей пикселей 1000x1000. Сначала все элементы матрицы положим нулями, а на каждой итерации начиная с десятой будем присваивать единицу соответствующему пикселю этой матрицы. То, что получилось, можно нарисовать с помощью функции `plt.imshow(..., cmap='gray')`. Картинку лучше сделать побольше, предварив `imshow` вызовом `plt.figure(figsize=(20, 20))`.

In [165]:
def shrink_rotate(X, A, coef, angle):
    A = A * coef #mult
    X = X * coef #mult
    
    ax = A.real
    ay = A.imag
    ox = X.real
    oy = X.imag
    xone = ax + math.cos(angle) * (ox - ax) - math.sin(angle) * (oy - ay) #rotate
    yone = ay + math.sin(angle) * (ox - ax) + math.cos(angle) * (oy - ay) #rotate

    return complex(xone, yone)

# Your code here
z = 0.5 + 0.*1j
max_iter = 100000
funcs = [
    (lambda t: shrink_rotate(t, 0. + 1.*1j, coef=0.5, angle=0.)),
    (lambda t: shrink_rotate(t, 1. + 0.*1j, coef=0.5, angle=0.)),
    (lambda t: shrink_rotate(t, -1. + 0.*1j, coef=0.5, angle=0.))
]

for n_iter in range(max_iter):
    n_func = np.random.choice(len(funcs))
    z = funcs[n_func](z)
    
matrix = []
for i in range(1000):
    raw = []
    for j in range(1000):
        raw.append(raw)
    matrix.append(raw)
    


**Задание 5.5 [0.75 баллов]** Попробуйте объяснить, почему получается именно эта фигура.

---
Ваше объяснение

**Задание 5.6 [0.5 баллов]** Поэкспериментируйте с другими преобразованиями. Попробуйте найти какой-нибудь другой красиво выглядящий фрактал.

In [ ]:
# Your code here

## Часть 6 (бонус). Метод Гаусса или обратные матрицы?

**Задание 6.1 [1.5 балла]** Пусть нам дано матричное уравнение $Ax = B$, где $A$ – матрица размера $n\times n$, а $B$ – матрица размера $n\times m$ (отметим, что это уравнение можно интерпретировать как $m$ систем с векторными правыми частями и однаковыми левыми). Вообще говоря, методов решения таких уравнений очень много, но мы пока рассмотрим два из них, с которыми вы уже хорошо знакомы.
1. Метод Гаусса;
2. Умножение на обратную матрицу: $x = A^{-1}B$.

В этом задании вы попробуете ответить на вопрос о том, какой из этих методов эффективнее. Проведите два эксперимента:
- сравните скорости решения системы при фиксированном `m = 10` и `n`, изменяющемся в пределах от 10 до 1000, например, для `n=10, 50, 100, 200, 500, 1000` (рост числа неизвестных при фиксированном количестве правых частей);
- сравните скорости решения системы при фиксированном `n = 100` и `m`, меняющемся от 10 до 10000, например, для `m = 10, 100, 500, 1000, 2000, 5000, 10000` (рост числа правых частей при фиксированном числе неизвестных).

При проведении экспериментов не возбраняется использовать циклы `for`.

Эксперименты проведите на случайных матрицах, созданных с помощью функции `numpy.random.rand`. Постройте графики времени выполнения функции от размерности (лучше в логарифмическом масштабе). Сделайте выводы (в письменном виде!) о том, какой из методов оказывается лучше в каких обстоятельствах.

Чтобы всё это не казалось вам чёрной магией, найдите число операций (суммарно сложения, умножения и деления), необходимых для решения системы каждым из методов. Обратите внимания на члены суммарной степени 3 (суммарной по $m$ и $n$; члены меньшего порядка можете даже не считать). Постарайтесь объяснить полученные ранее результаты.

In [ ]:
# Your code here